version: '3.7'

services:
  edgedb:
    image: edgedb/edgedb:latest
    volumes:
      - edgedb_data:/var/lib/edgedb/data
      - ../database:/app/database
    working_dir: /app/database
    ports:
      - "5656:5656"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_ADMIN_UI: enabled
      EDGEDB_SERVER_PASSWORD: password

volumes:
    edgedb_data: